name: statbotics
description: A library for retrieving information about team performance, event outcomes by offering methods to make HTTP requests to the Statbotics API.
version: 1.0.2
repository: https://github.com/DanPeled/statbotics-dart/

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
